name: Java CI

on:
  push:
  schedule: [ cron: '17 1 * * 4' ] # weekly: At 01:17 on Thursday

jobs:
  build:
    strategy:
      matrix:
        profile: [ resteasy, jetty ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'

    - run: mvn --batch-mode --show-version --no-transfer-progress -DCI=GitHub install -P${{ matrix.profile }}
